name: Update organization

on:
  push:
    branches:
      - master

jobs:
  peribolos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run peribolos
        run: ./peribolos.sh ${{ secrets.PERIBOLOS_TOKEN }}
